# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

gems: [jekyll-paginate]
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
#highlighter: pygments
highlighter: rouge
markdown: kramdown
disqus: dbyll
# google_analytics:
# rss_path: feed.xml
BASE_PATH:

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Tormentor's Blog

favicon: /assets/ico/favicon.png

author:
  name: Tormentor
  email: cn.sumknot@gmail.com
  github: sumknot
  # twitter: dbtek
  # pinterest: asd123
  # linkedin: asd123
  xiami: http://www.xiami.com/u/25766066
  avatar: /assets/image/avatar.jpg
  avatar_size: 240
  avatar_title_link:
  bio: This city is guilty, the crime is life, the sentence is death, darkness descendes!
  # email_md5: 726351295ec82e145928582f595aa3aa

menu:
  categories_path: categories.html
  tags_path: tags.html

strings:
  tab: "&#160; &#160; &#160; &#160;"
  crlf: "<br />"
  avatar_title:
  home: 主页
  categories: 分类
  tags: 标签
  top_of_page: 回到顶部
  previous_article: 上一篇
  next_article: 下一篇
  previous_page: 上一页
  next_page: 下一页
